# Configuraci√≥n por defecto:
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret elevation 
  unit_system: metric
  temperature_unit: C
  time_zone: !secret timezone
  packages: !include_dir_named integrations
  customize: !include customize.yaml
  
lovelace:
  mode: yaml
  
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest
  
person:
  - name: Alejandro
    id: !secret id
    device_trackers:
      - device_tracker.my_phone
      
weather:
  - platform: openweathermap
    api_key: !secret openweathermapkeyforweather
    mode: daily
    
updater:
  include_used_components: true
  
config:
conversation:
history:
logbook:
map:
mobile_app:
api:
ssdp:
sun:
http:
stream:
system_health:
zeroconf:
discovery:
media_extractor:

# Otras ubicaciones:
zone:
  - name: Location 1
    latitude: !secret location1_latitude 
    longitude: !secret location1_longitude  
    radius: 100

  - name: Location 2
    latitude: !secret location2_latitude 
    longitude: !secret location2_longitude  
    radius: 100

  - name: Location 3
    latitude: !secret location3_latitude 
    longitude: !secret location3_longitude  
    radius: 100

# Text to speech:
tts:
  - platform: google_translate
    language: es

# Google:
google:
  client_id: !secret googleID
  client_secret: !secret googleSecret
  track_new_calendar: true

# InfluxDB:
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret database
  username: !secret influxUser
  password: !secret influxPass
  max_retries: 3
  default_measurement: state

# Icons for Home Assistant:
panel_iframe:
  tautulli:
    title: Tautulli
    icon: mdi:filmstrip
    url: http://ip_from_tautulli:8181

# Add:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# HACS:
hacs:
  token: !secret hacs_token
  sidepanel_title: HACS
  sidepanel_icon: mdi:alpha-c-box
  appdaemon: true
  netdaemon: true
  release_limit: 5
  experimental: true

# Xiaomi Gateways: No longer supported. Now integrated via Lovelace
#xiaomi_aqara:
#  discovery_retry: 15
#  gateways:
#    - key: !secret keyAqaraV2

# Switch:
sonoff:
  username: !secret eweLinkUser
  password: !secret eweLinkPass
  scan_interval: 60
  grace_period: 600
  api_region: 'eu'
  entity_prefix: true
  debug: false
