homeassistant:
  packages: !include_dir_named integrations
  customize: !include customize.yaml

api:
config:
conversation:
history:
logbook:
map:
mobile_app:
person:
ssdp:
sun:
stream:
system_health:
discovery:
media_extractor:
zeroconf:
cloud:
webhook:
dhcp:
updater:
blueprint:
tag:
energy:
utility_meter:

# Remote access
http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Database
recorder:
  auto_purge: true

# Frontend
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate
    language: es

# InfluxDB
influxdb:
  host: !secret influx_host
  port: !secret influx_port
  database: !secret influxDB
  username: !secret influxDBusername
  password: !secret influxDBpassword
  max_retries: 3
  default_measurement: state

# Panel lateral
panel_iframe:
  tautulli:
    title: "Tautulli"
    icon: mdi:filmstrip
    url: !secret tautulli_URL
  networkmap:
    title: "Zigbee Map"
    url: !secret zigbee_URL
    icon: "mdi:graphql"

# Otras ubicaciones
zone:
  - name: Secret Place
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 100
    icon: mdi:home-city

# Google Calendar
google:
  client_id: !secret googleCalendarId
  client_secret: !secret googleCalendarSecret
  track_new_calendar: true

# Notify
notify_events:
  token: !secret notifyApi

# HACS
hacs: 
  token: !secret tokenHacs
  sidepanel_title: "HACS"
  sidepanel_icon: "mdi:store"
  appdaemon: true
  netdaemon: true
  release_limit: 5
  experimental: true

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_boolean: !include input_boolean.yaml
timer: !include timer.yaml
sensor: !include sensor.yaml
input_text: !include input_text.yaml

# Otros
bodymiscale: !include components/bodymiscale.yaml
